{
 "title": "華電AFC儲能一號場",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "R相電壓(KV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_a / 100 as phv_A \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_a / 100 as phv_A \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "S相電壓(KV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_b / 100 as phv_B \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_b / 100 as phv_B \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "T相電壓(KV)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_c / 100 as phv_C \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_c / 100 as phv_C \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "R相電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, current_a / 100 as current_A\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, current_a / 100 as current_A\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "S相電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, current_b / 100 as current_B \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, current_b / 100 as current_B \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "T相電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, current_c / 100 as current_C \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, current_c / 100 as current_C \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "頻率(Hz)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, frequency / 100\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, frequency / 100\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "實功率(KW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, total_watt / 100\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, total_watt / 100\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "虛功率(KVar)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, total_var / 100\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, total_var / 100\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "功率因數(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, power_factor \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, power_factor \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SOC(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, soc  \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, soc  \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ESS State",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, ess_state  \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, ess_state  \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}