{
 "title": "華電AFC輔助服務",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "整體服務資訊(報價代碼)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "執行率(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, execution_rate/100 as 執行率 FROM group_performance",
     "rawQueryText": "SELECT timestamp as time, execution_rate/100 as 執行率 FROM group_performance",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "實功率(KW)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, totalWatt/100 as 實功率 FROM group_real_power",
     "rawQueryText": "SELECT timestamp as time, totalWatt/100 as 實功率 FROM group_real_power",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "電網頻率(Hz)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, frequency / 100\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, frequency / 100\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "儲能一場(交易資源)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "R相電壓(V)、電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_a as phv_A \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_a as phv_A \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT timestamp as time,  current_a / 100 as current_A\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time,  current_a / 100 as current_A\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "S相電壓(KV)、電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_b as phv_B \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_b as phv_B \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT timestamp as time,  current_b / 100 as current_B\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time,  current_b / 100 as current_B\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "T相電壓(V)、電流(A)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, phv_c  as phv_C \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, phv_c  as phv_C \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT timestamp as time,  current_c / 100 as current_C\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time,  current_c / 100 as current_C\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "功率因數(%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, power_factor/100 as Power_Factor\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, power_factor/100 as Power_Factor\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT timestamp as time, soc/100 as SOC\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, soc/100 as SOC\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "實功率(KW)、虛功率(KVar)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 20 },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, total_watt / 100 as Total_Watt\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, total_watt / 100 as Total_Watt\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT timestamp as time, total_var / 100 as Total_Var\nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, total_var / 100 as Total_Var\nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "ESS State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, ess_state  \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, ess_state  \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "電池含量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, soc/100 as 電池含量  \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, soc/100 as 電池含量  \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "功率因數",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT timestamp as time, power_factor/100 as 功率因數  \nFROM resource_measurement",
     "rawQueryText": "SELECT timestamp as time, power_factor/100 as 功率因數  \nFROM resource_measurement",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}