baseURL = ""
languageCode = "zh-tw"
title = "Yellow Beach Full of Boobs：精神盪漾的海灘"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
relativeURLs = true

[params]
  author = "kendrivepolo"
  description = "基於興趣而建立的個人片庫"
  message = ""
  hideAutoMenu = false

[taxonomies]
  tag = "tags"
  category = "categories"
  actor = "actors"
  actress = "actresses"

[[menu.main]]
  name = "Sex Positions"
  url = "http://bestsexpositions.com"

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
