FROM aiothwacom/python:debian

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# need gcc for uwsgi
RUN apt-get update
RUN apt-get install -y gcc

# install dependencies
COPY requirements-flask-uwsgi.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# clean up
RUN apt-get purge -y --auto-remove gcc
