#FROM debian:buster

#RUN apt -y update
#RUN apt -y install build-essential
#RUN apt -y install default-jdk

FROM alpine:latest

RUN apk add --no-cache --virtual .build-deps gcc libc-dev linux-headers make openjdk11-jre bash



