#!/bin/sh

#JAVA_HOME="/home/ctu/jdk1.6.0_26"
#CATALINA_PID=`cat /home/ctu/tmp/catalina.pid`

# $CATALINA_PID's value is a file containing the pid in the .catalinarc 
. ${HOME}/.catalinarc
CATALINA_PID="$(cat "${CATALINA_PID}")"

NGC=`$JAVA_HOME/bin/jstat -gcnewcapacity $CATALINA_PID | tail -n 1 | cut -b 25-32`
OGC=`$JAVA_HOME/bin/jstat -gcoldcapacity $CATALINA_PID | tail -n 1 | cut -b 27-35`
CURRENT_TIME=`date +"%Y-%m-%d %H:%M:%S"`
PGC=`$JAVA_HOME/bin/jstat -gcmetacapacity $CATALINA_PID | tail -n 1 | cut -b 25-32`
echo "$CURRENT_TIME $NGC $OGC $PGC"
