# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

JAVA8_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/"
JAVA11_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home"
JAVA12_HOME="/Library/Java/JavaVirtualMachines/jdk-12.jdk/Contents/Home/"
JAVA_HOME=$JAVA11_HOME

KUBECONFIG=$HOME/.kube/config:$HOME/.kube/ews002

export JAVA8_HOME JAVA11_HOME JAVA12_HOME JAVA_HOME KUBECONFIG

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it
shopt -s histappend;

# Autocorrect typos in path names when using `cd`
shopt -s cdspell;

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
	shopt -s "$option" 2> /dev/null;
done;

# Add tab completion for many Bash commands
if which brew &> /dev/null && [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
	source "$(brew --prefix)/share/bash-completion/bash_completion";
elif [ -f /etc/bash_completion ]; then
	source /etc/bash_completion;
fi;

# Enable tab completion for `g` by marking it as an alias for `git`
if type _git &> /dev/null && [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
	complete -o default -o nospace -F _git g;
fi;

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults;

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

sshtunnel(){
    ssh -nNT -L 3306:kubuntu:3306 ken@kubuntu &
    ssh -nNT -L 27017:kubuntu:27017 ken@kubuntu &
    ssh -nNT -L 5672:kubuntu:5672 ken@kubuntu &
}

cl_sshtunnel(){
    ssh -nNT -L 27017:db-01:27017 devuser@db-03 &
}

oss_sshtunnel(){
    ssh -nNT -L 8092:oss.familyplus.com.tw:8092 devuser@oss.familyplus.com.tw &
}

rd(){
    echo $1 | tr '\.' ' ' | tr '\n' '\0' | pbcopy
}

switch_wise_paas(){
  kc config use-context 346d9f2b-8aa9-11ea-8847-02e0ba9e65ee-ews002
  kc config set-context --current --namespace hwacomapm
}

export BC_ENV_ARGS="/Users/huzhongwei/.bc"
export BASH_SILENCE_DEPRECATION_WARNING=1

source $HOME/.aliases

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/huzhongwei/google-cloud-sdk/path.bash.inc' ]; then . '/Users/huzhongwei/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/huzhongwei/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/huzhongwei/google-cloud-sdk/completion.bash.inc'; fi

